version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: message_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  messanger:
    build: .
    container_name: messanger-backend
    command:
      - ./main
    ports:
      - "3009:3009"
      - "3010:3010"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data: